# vars.yml
kafka_version: "3.5.1"
scala_version: "2.13"
kafka_download_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
kafka_install_dir: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
zookeeper_data_dir: "/var/lib/zookeeper"

# cmak
cmak_install_dir: "/opt/cmak"
cmak_download_url: "https://github.com/yahoo/CMAK/releases/download/v3.0.0.5/cmak-3.0.0.5.zip"
cmak_port: 9000