# Kafka 관련 설정
kafka_version: 3.9.0
kafka_install_dir: /opt/kafka
kafka_data_dir: /var/lib/kafka
kafka_backup_dir: /var/lib/kafka-backup

kafka_port: 9092
controller_port: 9093

kraft_metadata_dir: /var/lib/kafka/metadata
kafka_new_package: kafka_3.9.0.tgz

cluster_id: kraft-cluster-1

scala_version: 2.13
kafka_download_url: https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz

# kraft 설정
controller_quorum_voters: 1@broker1:9093,2@broker2:9093,3@broker3:9093

# CMAK 관련 설정
cmak_version: 3.0.0.7
cmak_install_dir: /opt/cmak
cmak_download_url: https://github.com/yahoo/CMAK/releases/download/{{ cmak_version }}/cmak-{{ cmak_version }}.tgz
cmak_port: 9000