# Kafka 관련 설정
kafka_version: "3.5.1"
scala_version: "2.13"
kafka_download_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

# CMAK 관련 설정
cmak_version: "3.0.0.7"
cmak_install_dir: "/opt/cmak"
cmak_download_url: "https://github.com/yahoo/CMAK/releases/download/{{ cmak_version }}/cmak-{{ cmak_version }}.tgz"
cmak_port: 9000