---
- name: Update Kafka binaries
  copy:
    src: "/tmp/kafka_{{ kafka_version }}/"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    owner: kafka
    group: kafka
    mode: "0755"

- name: Update inter.broker.protocol.version
  lineinfile:
    path: "{{ kafka_install_dir }}/config/server.properties"
    regexp: '^inter.broker.protocol.version='
    line: "inter.broker.protocol.version={{ kafka_version }}"
    backup: yes
