---
- name: Download CMAK binaries
  get_url:
    url: "{{ cmak_download_url }}"
    dest: "/tmp/cmak.tgz"

- name: Extract CMAK binaries
  unarchive:
    src: "/tmp/cmak.tgz"
    dest: "{{ cmak_install_dir }}"
    remote_src: yes

- name: Set permissions for CMAK
  file:
    path: "{{ cmak_install_dir }}"
    owner: kafka
    group: kafka
    recurse: yes
