---
- name: Start Kafka service
  systemd:
    name: kafka
    state: started
    enabled: true

- name: Verify Kafka service is running
  systemd:
    name: kafka
    state: started
  register: kafka_service_status

- name: Wait for Kafka broker to be ready
  wait_for:
    host: "{{ ansible_host }}"
    port: 9092
    state: started
    timeout: 30
  when: kafka_service_status.state == 'started'
