---
- name: Stop Kafka service
  systemd:
    name: kafka
    state: stopped

- name: Backup existing Kafka installation
  copy:
    src: "{{ kafka_install_dir }}"
    dest: "{{ kafka_backup_dir }}/{{ inventory_hostname }}"
    remote_src: yes
  when: kafka_install_dir is defined

- name: Download Kafka package if not present
  get_url:
    url: "{{ kafka_download_url }}"
    dest: "/tmp/{{ kafka_new_package }}"
  when: not kafka_package_stat.stat.exists

- name: Extract Kafka package
  unarchive:
    src: "/tmp/{{ kafka_new_package }}"
    dest: "/tmp"
    remote_src: yes

- name: Update Kafka binaries
  copy:
    src: "/tmp/kafka_{{ kafka_version }}/"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    owner: kafka
    group: kafka
    mode: "0755"

- name: Update inter.broker.protocol.version
  lineinfile:
    path: "{{ kafka_install_dir }}/config/server.properties"
    regexp: '^inter.broker.protocol.version='
    line: "inter.broker.protocol.version={{ kafka_version }}"
    backup: yes
