---
- name: Download CMAK binaries
  get_url:
    url: "{{ cmak_download_url }}"
    dest: "/tmp/cmak.tgz"

- name: Extract CMAK binaries
  unarchive:
    src: "/tmp/cmak.tgz"
    dest: "{{ cmak_install_dir }}"
    remote_src: yes

- name: Set permissions for CMAK
  file:
    path: "{{ cmak_install_dir }}"
    owner: kafka
    group: kafka
    recurse: yes---

- name: Deploy CMAK configuration
  template:
    src: cmak.conf.j2
    dest: "{{ cmak_install_dir }}/conf/application.conf"
    owner: kafka
    group: kafka

- name: Deploy CMAK systemd service
  copy:
    src: cmak.service
    dest: /etc/systemd/system/cmak.service
    mode: 0644

- name: Reload systemd and enable CMAK
  systemd:
    name: cmak
    enabled: yes
    state: started
