---
- hosts: all
  gather_facts: no
  vars_files:
    - "inventory/vars.yml"
  roles:
    - install_pre

- hosts: kafka
  gather_facts: no
  vars_files:
    - "inventory/vars.yml"
  roles:
    - install_kafka
