---
- name: Install prerequisites
  hosts: all
  become: yes
  tasks:
    - include_tasks: tasks/install_prerequisites.yml

- name: Install Kafka and CMAK
  hosts: kafka_servers
  become: yes
  vars_files:
    - vars/vars.yml
  tasks:
    - include_tasks: tasks/install_kafka.yml
    - include_tasks: tasks/configure_kafka.yml

- name: Install CMAK
  hosts: cmak_servers
  become: yes
  vars_files:
    - vars/vars.yml
  tasks:
    - include_tasks: tasks/install_cmak.yml
    - include_tasks: tasks/configure_cmak.yml